[font]
size = 14.0

[font.normal]
family = "Inconsolata Nerd Font Mono"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[shell]
args = ["-l", "-c", "tmux new -As0"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
