#!/bin/bash
set -euxo pipefail

# install Brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install dependencies
brew bundle
pip3 install neovim

# install tmux plugin
git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

# fzf
$(brew --prefix)/opt/fzf/install

# install vim-plug
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qa

# aliases
ln -s ~/.config/tmux/tmux.conf ~/.tmux.conf
ln -s ~/.config/bash/bash_profile ~/.bash_profile
ln -s ~/.config/git/gitconfig ~/.gitconfig
ln -s ~/.config/git/gitignore ~/.gitignore
ln -s ~/.config/.ctags ~/.ctags

# KeyRepeat stuff
defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

# install node
local nvm_dir="$HOME/.nvm"
[ -s "$nvm_dir/nvm.sh" ] && source "$nvm_dir/nvm.sh"  # This loads nvm
nvm install 12
