#!/bin/bash
set -euxo pipefail

# clone this repo
git clone https://github.com/igoratron/dotfiles.git ~/.config

# install Brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install dependencies
cd ~/.config
brew bundle
pip3 install pynvim

# install tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

# fzf
$(brew --prefix)/opt/fzf/install

# install vim stuff
git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
vim +PackerSync +qa

# install node
nvm install 15

# profile image
dscl . -read /Users/${USER} JPEGPhoto | tail -1 | xxd -r -p > ${HOME}/Pictures/accountImage.jpg

# aliases
ln -s ~/.config/tmux/tmux.conf ~/.tmux.conf
ln -s ~/.config/git/gitconfig ~/.gitconfig
ln -s ~/.config/git/gitignore ~/.gitignore
ln -s ~/.config/mtmr/items.json ~/Library/Application\ Support/MTMR/items.json

# Change minimize/maximize window effect
defaults write com.apple.dock mineffect -string "scale"

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Set MacOS defaults
osascript -e 'tell application "System Preferences" to quit'

# Set the dock to autohide
defaults write com.apple.Dock autohide 1

# Put dock on the left
defaults write com.apple.dock "orientation" -string "left"

dockutil --remove all
dockutil --add /Applications/Alacritty.app
dockutil --add /Applications/Firefox.app
dockutil --add /Applications/Slack.app
killall Dock
